image: ubuntu:18.04

build:
  stage: build
  before_script:
    - apt update
    - apt install -y --no-install-recommends wget gnupg ca-certificates python3 python python3-distutils
    - wget -qO - https://bazel.build/bazel-release.pub.gpg | apt-key add -
    - echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
    - apt update
    - apt install -y --no-install-recommends bazel-2.1.0
  script:
    - cd test/hello-world
    - bazel-2.1.0 build //...
