package(default_visibility = ['//visibility:public'])

load("@rules_python//python:defs.bzl", "py_binary")
load("@pip_deps//:requirements.bzl", "requirement")

py_binary(
    name = "icon3",
    srcs = ["icon3.py"],
    deps = [
        requirement("pillow"),
    ],
)

cc_library(
    name = "sdk",
    srcs = [
        "include/os.h",
        "include/bolos_target.h",
        "include/os_hal.h",
        "include/core_sc000.h",
        "include/core_cmInstr.h",
        "include/core_cmFunc.h",
        "include/os_apilevel.h",
        "include/cx.h",
        "include/lcx_common.h",
        "include/lcx_rng.h",
        "include/lcx_hash.h",
        "include/lcx_ripemd160.h",
        "include/lcx_sha256.h",
        "include/lcx_sha3.h",
        "include/lcx_sha512.h",
        "include/lcx_blake2.h",
        "include/lcx_groestl.h",
        "include/lcx_hmac.h",
        "include/lcx_pbkdf2.h",
        "include/lcx_des.h",
        "include/lcx_aes.h",
        "include/lcx_rsa.h",
        "include/lcx_ecfp.h",
        "include/lcx_ecdsa.h",
        "include/lcx_ecschnorr.h",
        "include/lcx_eddsa.h",
        "include/lcx_ecdh.h",
        "include/lcx_crc.h",
        "include/lcx_math.h",
        "include/cx_compliance_141.h",
        "include/syscalls.h",
        "include/seproxyhal_protocol.h",
        "include/os_io_usb.h",
        "include/os_io_seproxyhal.h",
        "include/bagl.h",
        "src/syscalls.c",
        "src/os.c",
        "src/os_io_seproxyhal.c",
        "src/cx.c",
        "src/pic.c",
        "src/pic_internal.c",
        "src/os_io_usb.c",
        "src/tcr.c",
        "src/os_printf.c",

        # ux
        "lib_ux/include/ux.h",
        "lib_ux/include/ux_layouts.h",
        "lib_ux/include/ux_flow_engine.h",
        "lib_ux/src/ux_layout_common.h",
        "lib_ux/src/ux_stack.c",
        "lib_ux/src/ux_layout_pb.c",
        "lib_ux/src/ux_layout_bnn.c",
        "lib_ux/src/ux_layout_bn.c",
        "lib_ux/src/ux_layout_utils.c",
        "lib_ux/src/ux_flow_engine.c",
        "lib_ux/src/ux_layout_paging.c",
        "lib_ux/src/ux_layout_bb.c",
        "lib_ux/src/ux_layout_nn.c",
        "lib_ux/src/ux_layout_pnn.c",
        "lib_ux/src/ux_layout_pbb.c",
        "lib_ux/src/ux_menulist.c",
        "lib_ux/src/ux_layout_nnbnn.c",

        # u2f
        "lib_u2f/include/u2f_service.h",
        "lib_u2f/include/u2f_processing.h",
        "lib_u2f/include/u2f_transport.h",
        "lib_u2f/include/u2f_io.h",
        "lib_u2f/src/u2f_transport.c",

        # usb
        "lib_stusb_impl/u2f_impl.h",
        "lib_stusb_impl/u2f_io.c",
        "lib_stusb_impl/u2f_impl.c",
        "lib_stusb_impl/usbd_impl.c",
        "lib_stusb_impl/usbd_hid_impl.h",
        "lib_stusb/usbd_conf.c",
        "lib_stusb/usbd_conf.h",
        "lib_stusb/STM32_USB_Device_Library/Class/HID/Src/usbd_hid.c",
        "lib_stusb/STM32_USB_Device_Library/Class/HID/Inc/usbd_hid.h",
        "lib_stusb/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c",
        "lib_stusb/STM32_USB_Device_Library/Core/Inc/usbd_ioreq.h",
        "lib_stusb/STM32_USB_Device_Library/Core/Inc/usbd_def.h",
        "lib_stusb/STM32_USB_Device_Library/Core/Src/usbd_core.c",
        "lib_stusb/STM32_USB_Device_Library/Core/Inc/usbd_core.h",
        "lib_stusb/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c",
        "lib_stusb/STM32_USB_Device_Library/Core/Inc/usbd_ctlreq.h",
    ],
    hdrs = [
        "include/os.h",
        "include/cx.h",
        "include/ux.h",
    ],
    deps = [
        ":script.ld",
    ],
    strip_include_prefix = "include",
    include_prefix = "ledger",
    includes = [
        "include",
        "lib_ux/include",
        "lib_stusb/STM32_USB_Device_Library/Class/HID/Inc",
        "lib_stusb/STM32_USB_Device_Library/Core/Inc/",
        "lib_stusb",
        "lib_stusb_impl",
        "lib_u2f/include",
    ],
    copts = [
       "-std=gnu99",
        "-Wall",
        "-Werror",
        "-Wno-error=#warnings",
        "-Wno-error=missing-declarations",
        "-Wno-error=int-conversion",
    ],
    linkopts = [
        "-T$(location :script.ld)",
    ],
)